name: heart-failure-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - dvc
  - ipython
  - jupyterlab
  - loguru
  - matplotlib
  - mkdocs
  - notebook
  - numpy
  - pandas
  - pip
  - plotly
  - pre-commit
  - pyright[nodejs]
  - pytest
  - pytest-cov
  - python-dotenv
  - rich
  - ruff
  - scikit-learn
  - scipy
  - seaborn
  - streamlit
  - pip:
      - -e .
