version: "3"

vars:
  lib: heart-failure-prediction
  python_version: 3.12
  python_interpreter: python

tasks:
  setup:
    desc: Set up Anaconda environment
    cmds:
      - conda env create --name {{.lib}}

  install:
    desc: Install dependencies
    cmds:
      - conda env update --name {{.lib}} --prune

  clean:
    desc: Clean up artifacts
    summary: Delete all build, test, coverage, and Python artifacts.
    cmds:
      - find . -type f -name "*.py[co]" -delete
      - find . -type d -name "__pycache__" -delete

  pre-commit:
    desc: Run pre-commit hooks
    summary: |
      Run pre-commit hooks.
      Runs all pre-commit hooks.
    cmds:
      - pre-commit run

  pre-commit-all:
    desc: Run pre-commit hooks on all files
    summary: |
      Run pre-commit hooks on all files.
      Runs all pre-commit hooks on all files in the repository.
    cmds:
      - pre-commit run --all-files

  lint:
    desc: Run linter
    summary: |
      Run linting checks.
      Lints all files using the Ruff linter.
    cmds:
      - ruff check

  lint-fix:
    desc: Run linter with auto-fix
    summary: |
      Run linting checks with auto-fix.
      Lints all files using the Ruff linter, and fixes any fixable errors.
    cmds:
      - ruff check --fix --show-fixes

  format:
    desc: Run formatter
    summary: |
      Run formatting.
      Formats source code using the Ruff formatter.
    cmds:
      - ruff format

  format-check:
    desc: Run format checker
    summary: |
      Run formatting checks.
      Checks source code formatting using the Ruff formatter.
    cmds:
      - ruff format --check

  typecheck:
    desc: Run type-checker
    summary: |
      Run static type checks.
      Type-checks using Pyright.
    cmds:
      - pyright

  typecheck-stats:
    desc: Run type-checker with stats
    summary: |
      Run static type checks with stats.
      Type-checks using Pyright, and shows stats.
    cmds:
      - pyright --stats

  test:
    desc: Run tests
    summary: |
      Run all test cases.
      Tests using pytest.
    cmds:
      - pytest

  check-all:
    desc: Run all checks and tests
    summary: Run lint, typecheck, format-check and test tasks.
    cmds:
      - task: lint
      - task: typecheck
      - task: format-check
      - task: test

  check-all-fix:
    desc: Run all checks and tests with auto-fix
    summary: Run lint-fix, typecheck, format and test tasks.
    cmds:
      - task: lint-fix
      - task: typecheck
      - task: format
      - task: test
